# Site settings
title: Patrick Kraft | Ph.D. Candidate in the Department of Political Science at Stony Brook University
email: patrick.kraft@stonybrook.edu
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Patrick W. Kraft
affiliation: Stony Brook University

# Social icons
github: pwkraft
linkedin: patrick-kraft-b52319101
researchgate: Patrick_Kraft2
#facebook: username
#deviantart: username
#codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
